// 演示用种子数据（日期相对今天生成，保证排产台看起来是"活"的）
import type {
  ColorCard,
  DyeSlot,
  Pattern,
  Receipt,
  RepairBatch,
} from "./types";
import { addDays, todayStr } from "./utils";

const t = todayStr();
const d = (n: number) => addDays(t, n);

export function seedPatterns(): Pattern[] {
  return [
    {
      id: "PAT-001",
      name: "波斯·狩猎纹地毯残片",
      origin: "波斯",
      era: "约1900s",
      knotDensity: "42 结/英寸",
      material: "羊毛",
      dyeType: "植物染",
      damageArea: "边缘磨损、补线脱落",
      threadColor: "靛蓝",
      process: "清洗 → 补线 → 染色固色",
      beforeNote: "边缘经纱外露约 15cm，补线脱落",
      afterNote: "补线完成，靛蓝固色，待上机染色",
      createdAt: Date.now() - 86400000 * 30,
    },
    {
      id: "PAT-002",
      name: "安纳托利亚·祈祷纹",
      origin: "安纳托利亚",
      era: "约1900s",
      knotDensity: "36 结/英寸",
      material: "羊毛",
      dyeType: "植物染",
      damageArea: "中心纹样缺口",
      threadColor: "茜草红",
      process: "补缺 → 染色 → 整理",
      createdAt: Date.now() - 86400000 * 28,
    },
    {
      id: "PAT-003",
      name: "高加索·星纹挂毯",
      origin: "高加索",
      era: "约1920s",
      knotDensity: "40 结/英寸",
      material: "羊毛",
      dyeType: "植物染",
      damageArea: "局部褪色",
      threadColor: "核桃棕",
      process: "清洗 → 套染 → 固色",
      createdAt: Date.now() - 86400000 * 20,
    },
    {
      id: "PAT-004",
      name: "藏毯·龙纹靠背",
      origin: "藏毯",
      era: "约1950s",
      knotDensity: "30 结/英寸",
      material: "羊毛",
      dyeType: "化学染",
      damageArea: "边角破损",
      threadColor: "藏蓝",
      process: "缝补 → 染色 → 上浆",
      createdAt: Date.now() - 86400000 * 15,
    },
    {
      id: "PAT-005",
      name: "波斯·花卉纹丝毛毯",
      origin: "波斯",
      era: "约1930s",
      knotDensity: "46 结/英寸",
      material: "丝毛混纺",
      dyeType: "植物染",
      damageArea: "破洞补织",
      threadColor: "槐黄",
      process: "补织 → 套色 → 整理",
      createdAt: Date.now() - 86400000 * 10,
    },
    {
      id: "PAT-006",
      name: "安纳托利亚·双联纹",
      origin: "安纳托利亚",
      era: "约1960s",
      knotDensity: "34 结/英寸",
      material: "羊毛",
      dyeType: "植物染",
      damageArea: "开线加固",
      threadColor: "铁锈红",
      process: "加固 → 染色 → 固色",
      createdAt: Date.now() - 86400000 * 8,
    },
  ];
}

export function seedCards(): ColorCard[] {
  return [
    { id: "COL-001", name: "靛蓝", hex: "#1e3a5f", batch: "B-2609", material: "羊毛", stockKg: 12, unit: "kg" },
    { id: "COL-002", name: "茜草红", hex: "#9b2c2c", batch: "B-2608", material: "羊毛", stockKg: 8, unit: "kg" },
    { id: "COL-003", name: "核桃棕", hex: "#6b4423", batch: "B-2607", material: "羊毛", stockKg: 15, unit: "kg" },
    { id: "COL-004", name: "藏蓝", hex: "#274472", batch: "B-2609", material: "羊毛", stockKg: 6, unit: "kg" },
    { id: "COL-005", name: "槐黄", hex: "#d4a017", batch: "B-2606", material: "丝毛", stockKg: 5, unit: "kg" },
    { id: "COL-006", name: "铁锈红", hex: "#a0522d", batch: "B-2605", material: "羊毛", stockKg: 9, unit: "kg" },
  ];
}

export function seedSlots(): DyeSlot[] {
  return [
    { id: "VAT-01", name: "东染槽", capacityKg: 30, status: "运行中", location: "一号车间" },
    { id: "VAT-02", name: "西染槽", capacityKg: 50, status: "运行中", location: "一号车间" },
    { id: "VAT-03", name: "南染槽", capacityKg: 80, status: "运行中", location: "二号车间" },
    { id: "VAT-04", name: "北染槽", capacityKg: 30, status: "维护中", location: "二号车间" },
  ];
}

export function seedBatches(): RepairBatch[] {
  return [
    {
      id: "BAT-001",
      patternId: "PAT-001",
      colorCardId: "COL-001",
      colorCardBatch: "B-2609",
      usageKg: 2.5,
      weightKg: 18,
      days: 3,
      urgency: "特急",
      dueDate: d(5),
      source: "馆藏借展",
      slotId: "VAT-01",
      plannedStart: d(-1),
      plannedEnd: d(2),
      actualStart: d(-1),
      actualEnd: null,
      status: "染机上",
      outsourced: false,
      workshop: null,
      confirmed: true,
      legacy: false,
      createdAt: Date.now() - 86400000 * 6,
      note: "借展特急，开展前必须入库",
    },
    {
      id: "BAT-002",
      patternId: "PAT-002",
      colorCardId: "COL-002",
      colorCardBatch: "B-2608",
      usageKg: 1.8,
      weightKg: 12,
      days: 2,
      urgency: "加急",
      dueDate: d(3),
      source: "私人订单",
      slotId: "VAT-02",
      plannedStart: d(-2),
      plannedEnd: d(0),
      actualStart: d(-2),
      actualEnd: d(0),
      status: "已完工",
      outsourced: false,
      workshop: null,
      confirmed: true,
      legacy: false,
      createdAt: Date.now() - 86400000 * 5,
    },
    {
      id: "BAT-003",
      patternId: "PAT-003",
      colorCardId: "COL-003",
      colorCardBatch: "B-2607",
      usageKg: 3.0,
      weightKg: 22,
      days: 4,
      urgency: "普通",
      dueDate: d(13),
      source: "馆藏借展",
      slotId: "VAT-03",
      plannedStart: d(1),
      plannedEnd: d(5),
      actualStart: null,
      actualEnd: null,
      status: "已占位",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: false,
      createdAt: Date.now() - 86400000 * 4,
    },
    {
      id: "BAT-004",
      patternId: "PAT-004",
      colorCardId: "COL-004",
      colorCardBatch: "B-2609",
      usageKg: 2.0,
      weightKg: 16,
      days: 3,
      urgency: "特急",
      dueDate: d(2),
      source: "私人订单",
      slotId: null,
      plannedStart: null,
      plannedEnd: null,
      actualStart: null,
      actualEnd: null,
      status: "待分配",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: false,
      createdAt: Date.now() - 86400000 * 1,
      note: "客户催单，要求加急占位",
    },
    {
      id: "BAT-005",
      patternId: "PAT-005",
      colorCardId: "COL-005",
      colorCardBatch: "B-2606",
      usageKg: 1.2,
      weightKg: 8,
      days: 2,
      urgency: "加急",
      dueDate: d(8),
      source: "外协",
      slotId: "VAT-02",
      plannedStart: d(2),
      plannedEnd: d(4),
      actualStart: null,
      actualEnd: null,
      status: "已占位",
      outsourced: true,
      workshop: "云染坊",
      confirmed: false,
      legacy: false,
      createdAt: Date.now() - 86400000 * 3,
    },
    {
      id: "BAT-006",
      patternId: "PAT-006",
      colorCardId: "COL-006",
      colorCardBatch: "B-2605",
      usageKg: 2.2,
      weightKg: 15,
      days: 3,
      urgency: "普通",
      dueDate: d(18),
      source: "私人订单",
      slotId: null,
      plannedStart: null,
      plannedEnd: null,
      actualStart: null,
      actualEnd: null,
      status: "待分配",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: false,
      createdAt: Date.now() - 86400000 * 2,
    },
    {
      id: "BAT-007",
      patternId: "PAT-001",
      colorCardId: "COL-001",
      colorCardBatch: "B-2609",
      usageKg: 1.0,
      weightKg: 6,
      days: 1,
      urgency: "普通",
      dueDate: null,
      source: "馆藏借展",
      slotId: null,
      plannedStart: null,
      plannedEnd: null,
      actualStart: null,
      actualEnd: null,
      status: "待分配",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: true,
      createdAt: Date.now() - 86400000 * 400,
      note: "旧档案升级：原数据缺交期与槽位号",
    },
    {
      id: "BAT-008",
      patternId: "PAT-003",
      colorCardId: "COL-003",
      colorCardBatch: "B-2607",
      usageKg: 1.5,
      weightKg: 10,
      days: 2,
      urgency: "普通",
      dueDate: null,
      source: "私人订单",
      slotId: null,
      plannedStart: null,
      plannedEnd: null,
      actualStart: null,
      actualEnd: null,
      status: "待分配",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: true,
      createdAt: Date.now() - 86400000 * 360,
      note: "旧档案升级：原数据缺交期与槽位号",
    },
    {
      id: "BAT-009",
      patternId: "PAT-002",
      colorCardId: "COL-002",
      colorCardBatch: "B-2608",
      usageKg: 0.8,
      weightKg: 5,
      days: 1,
      urgency: "加急",
      dueDate: d(4),
      source: "馆藏借展",
      slotId: "VAT-01",
      plannedStart: d(2),
      plannedEnd: d(3),
      actualStart: null,
      actualEnd: null,
      status: "已占位",
      outsourced: false,
      workshop: null,
      confirmed: false,
      legacy: false,
      createdAt: Date.now() - 86400000 * 2,
    },
    {
      id: "BAT-010",
      patternId: "PAT-005",
      colorCardId: "COL-005",
      colorCardBatch: "B-2606",
      usageKg: 1.0,
      weightKg: 7,
      days: 2,
      urgency: "普通",
      dueDate: d(-2),
      source: "私人订单",
      slotId: "VAT-02",
      plannedStart: d(-6),
      plannedEnd: d(-4),
      actualStart: d(-6),
      actualEnd: d(-4),
      status: "已入库",
      outsourced: false,
      workshop: null,
      confirmed: true,
      legacy: false,
      createdAt: Date.now() - 86400000 * 12,
    },
  ];
}

export function seedReceipts(): Receipt[] {
  const now = Date.now();
  return [
    {
      id: "REC-001",
      batchId: "BAT-005",
      workshop: "云染坊",
      arrivedAt: now - 3600_000 * 2,
      colorCardBatch: "B-2606",
      usageKg: 1.2,
      status: "待对账",
    },
    {
      id: "REC-002",
      batchId: "BAT-006",
      workshop: "云染坊",
      arrivedAt: now - 3600_000 * 5,
      colorCardBatch: "B-2604",
      usageKg: 2.2,
      status: "待对账",
    },
    {
      id: "REC-003",
      batchId: "BAT-004",
      workshop: "苏绣坊",
      arrivedAt: now - 3600_000 * 8,
      colorCardBatch: "B-2609",
      usageKg: 2.5,
      status: "待对账",
    },
    {
      id: "REC-004",
      batchId: "BAT-010",
      workshop: "云染坊",
      arrivedAt: now - 3600_000 * 24,
      colorCardBatch: "B-2606",
      usageKg: 1.0,
      status: "迟到",
      reason: "工序已确认/已完工，后到回执仅留存，不改写已确认工序",
    },
    {
      id: "REC-005",
      batchId: "BAT-999",
      workshop: "云染坊",
      arrivedAt: now - 3600_000 * 26,
      colorCardBatch: "B-2609",
      usageKg: 1.0,
      status: "待对账",
    },
    {
      id: "REC-006",
      batchId: "BAT-002",
      workshop: "云染坊",
      arrivedAt: now - 3600_000 * 48,
      colorCardBatch: "B-2608",
      usageKg: 1.8,
      status: "已对账",
      reconciledAt: now - 3600_000 * 47,
    },
  ];
}
